#!/bin/bash

rm -rf test_scenario && mkdir test_scenario
mkdir test_scenario/FHS
mkdir test_scenario/PG

name=0;cat sets/guigo/g_ren.txt | while read g; do ((name+=1));dlsgen/dlsgen2 -gs -da -pilaEv  $g `cat sets/guigo/s_ren.txt`>test_scenario/PG/PG_$name.txt; done
name=0;cat sets/guigo/g_ren.txt | while read g; do ((name+=1));dlsgen/dlsgen2 -ga -da -pilaEv  $g `cat sets/guigo/s_ren.txt`>test_scenario/FHS/FHS_$name.txt; done


python3 reader.py `ls -d /home/alek/PycharmProjects/DLS_trees/test_scenario/FHS/*`
echo "---------------------------------------------"
python3 reader.py `ls -d /home/alek/PycharmProjects/DLS_trees/test_scenario/PG/*`