#!/usr/bin/env bash

spec=`cat sets/genolevures/s.txt`
rm -fs sets/genolevures/g_bin.txt
touch sets/genolevures/g_bin.txt
echo $spec
echo "urec..."
while read g; do
    echo "$g"
    ./urec/urec -g $g -s $spec -b -O>>sets/genolevures/g_bin.txt
done <sets/genolevures/g.txt